source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'jason', :path => '../../'

group :development, :test do
  gem 'minitest', '~> 2.0'
  gem 'mocha', '~> 0.9'
  gem 'autotest', '~> 4.4'
  gem 'json', '~> 1.5'
end